# Generated by Django 2.1.3 on 2018-11-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181116_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='designation',
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(choices=[(1, 'Student'), (2, 'Faculty'), (3, 'Staff')], default='', max_length=50, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
