# Generated by Django 2.1.3 on 2018-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181116_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='designation',
            field=models.CharField(choices=[(1, 'Student'), (2, 'Faculty'), (3, 'Staff')], default='', max_length=7, verbose_name=''),
        ),
    ]
