# Generated by Django 2.1.3 on 2018-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181116_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='designation',
            field=models.CharField(choices=[(1, '-------'), (2, 'Student'), (3, 'Faculty'), (4, 'Staff')], default='', max_length=7, verbose_name=''),
        ),
    ]
