# Generated by Django 2.1.3 on 2018-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181116_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='designation',
            field=models.IntegerField(choices=[(1, '-------'), (2, 'Student'), (3, 'Faculty'), (4, 'Staff')], default='', verbose_name='Designation'),
        ),
    ]
