# Generated by Django 2.1.3 on 2018-11-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181113_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(default='', null=True, upload_to='Uploads/', verbose_name='Image'),
        ),
    ]
