# Generated by Django 2.1.3 on 2018-11-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181114_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(default='', upload_to='Uploads/', verbose_name='Image'),
        ),
    ]
