# Generated by Django 2.1.3 on 2018-11-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20181116_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[(1, 'Institutional'), (2, 'Special')], default='', max_length=14, verbose_name='Event Type'),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
