# Generated by Django 2.1.3 on 2018-11-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20181116_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(1, 'Institutional'), (2, 'Special')], default='', max_length=14, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name of event'),
        ),
    ]
