# Generated by Django 2.1.3 on 2018-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20181116_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, '-------'), (2, 'Institutional'), (3, 'Special')], default='', max_length=14, verbose_name='Event Type'),
        ),
    ]
