# Generated by Django 2.1.3 on 2018-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20181116_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(choices=[(1, '-------'), (2, 'Institutional'), (3, 'Special')], default='', verbose_name='Event Type'),
        ),
    ]
