# Generated by Django 2.1.3 on 2018-11-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0004_auto_20181114_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.TimeField(verbose_name='For Date')),
                ('time_arrived', models.TimeField(verbose_name='Time Arrived')),
                ('time_left', models.TimeField(verbose_name='Time Left')),
                ('security_key', models.CharField(default='', max_length=8, verbose_name='Security Key')),
                ('registration_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrations.Registration')),
            ],
        ),
    ]
